import HomeView from '@/views/dashboard/eCommerceDashboard.vue'

export const pagesRoutes = [
    {
        path: '/',
        component: HomeView,
        name: 'dashboard_index',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/crm-dashboard',
        component: () => import('@/views/dashboard/CrmDashboard.vue'),
        name: 'crm_dashboard',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/hrm-dashboard',
        component: () => import('@/views/dashboard/HrmDashboard.vue'),
        name: 'hrm_dashboard',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/audience',
        component: () => import('@/views/apps/crm/Audience.vue'),
        name: 'crm_audience',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/company',
        component: () => import('@/views/apps/crm/Company.vue'),
        name: 'crm_company',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/task',
        component: () => import('@/views/apps/crm/Task.vue'),
        name: 'crm_task',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/leads',
        component: () => import('@/views/apps/crm/Leads.vue'),
        name: 'crm_leads',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/customer',
        component: () => import('@/views/apps/crm/Customer.vue'),
        name: 'crm_customer',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/add-employee',
        component: () => import('@/views/apps/hrm/AddEmployee.vue'),
        name: 'hrm_add_employee',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/all-employee',
        component: () => import('@/views/apps/hrm/AllEmployee.vue'),
        name: 'hrm_all_employee',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/attendance',
        component: () => import('@/views/apps/hrm/Attendance.vue'),
        name: 'hrm_attendance',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/all-customer',
        component: () => import('@/views/apps/ecommerce/AllCustomer.vue'),
        name: 'all_customer',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/add-product',
        component: () => import('@/views/apps/ecommerce/AddProduct.vue'),
        name: 'add_product',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/all-product',
        component: () => import('@/views/apps/ecommerce/AllProduct.vue'),
        name: 'all_product',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/category',
        component: () => import('@/views/apps/ecommerce/Category.vue'),
        name: 'category',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/order',
        component: () => import('@/views/apps/ecommerce/Order.vue'),
        name: 'order',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/calendar',
        component: () => import('@/views/apps/Calendar.vue'),
        name: 'calendar',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/chat',
        component: () => import('@/views/apps/Chat.vue'),
        name: 'chat',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/email',
        component: () => import('@/views/apps/Email.vue'),
        name: 'email',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/invoices',
        component: () => import('@/views/apps/Invoices.vue'),
        name: 'invoices',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/contact',
        component: () => import('@/views/apps/Contact.vue'),
        name: 'contact',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/view-profile',
        component: () => import('@/views/pages/user/ViewProfile.vue'),
        name: 'view_profile',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/edit-profile',
        component: () => import('@/views/pages/user/EditProfile.vue'),
        name: 'edit_profile',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/sweet-alert',
        component: () => import('@/views/components/advanceUI/SweetAlert.vue'),
        name: 'sweet_alert',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/nestable-list',
        component: () => import('@/views/components/advanceUI/NestableList.vue'),
        name: 'nestable_list',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/animation',
        component: () => import('@/views/components/advanceUI/Animation.vue'),
        name: 'animation',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/swiper-slider',
        component: () => import('@/views/components/advanceUI/SwiperSlider.vue'),
        name: 'swiper_slider',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/form',
        component: () => import('@/views/components/Form.vue'),
        name: 'form',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/table',
        component: () => import('@/views/components/Table.vue'),
        name: 'table',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/charts',
        component: () => import('@/views/components/Charts.vue'),
        name: 'charts',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/icon',
        component: () => import('@/views/components/Icon.vue'),
        name: 'icon',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/map',
        component: () => import('@/views/components/Map.vue'),
        name: 'map',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/file-manager',
        component: () => import('@/views/components/FileManager.vue'),
        name: 'file_manager',
        meta: { layout: 'AppLayout', isPartials: true },
    },
    {
        path: '/utility',
        component: () => import('@/views/pages/Utility.vue'),
        name: 'utility',
        meta: { layout: 'AppLayout', isPartials: true },
    },
];